export const AtendanceData = [
  {
    "title": "In -12:29 PM",
    "start": "2024-02-01",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "2",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Out- 5:26 PM",
    "start": "2024-02-01",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "3",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Total Time: 4:57",
    "start": "2024-02-01",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "4",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "In -12:23 PM",
    "start": "2024-02-02",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "2",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Friday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Out- 6:45 PM",
    "start": "2024-02-02",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "3",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Friday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Total Time: 6:22",
    "start": "2024-02-02",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "4",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Friday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "In -12:38 PM",
    "start": "2024-02-08",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "2",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Out- 5:39 PM",
    "start": "2024-02-08",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "3",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Total Time: 5:01",
    "start": "2024-02-08",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "4",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "In -12:18 PM",
    "start": "2024-02-14",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "2",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Wednesday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Out- 5:10 PM",
    "start": "2024-02-14",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "3",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Wednesday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Total Time: 4:52",
    "start": "2024-02-14",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "4",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Wednesday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "In -12:16 PM",
    "start": "2024-02-15",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "2",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Out- 5:48 PM",
    "start": "2024-02-15",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "3",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Total Time: 5:32",
    "start": "2024-02-15",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "4",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "In -11:38 AM",
    "start": "2024-02-16",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "2",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Friday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Out- 5:10 PM",
    "start": "2024-02-16",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "3",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Friday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Total Time: 5:32",
    "start": "2024-02-16",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "4",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Friday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "In -11:53 AM",
    "start": "2024-02-19",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "2",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Monday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Out- 5:57 PM",
    "start": "2024-02-19",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "3",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Monday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Total Time: 6:04",
    "start": "2024-02-19",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "4",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Monday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "In -11:51 AM",
    "start": "2024-02-20",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "2",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Tuesday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Out- 5:36 PM",
    "start": "2024-02-20",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "3",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Tuesday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Total Time: 5:45",
    "start": "2024-02-20",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "4",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Tuesday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "In -12:22 PM",
    "start": "2024-02-21",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "2",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Wednesday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Out- 7:19 PM",
    "start": "2024-02-21",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "3",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Wednesday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Total Time: 6:57",
    "start": "2024-02-21",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "4",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Wednesday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "In -12:36 PM",
    "start": "2024-02-22",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "2",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Out-",
    "start": "2024-02-22",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "3",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Total Time: 0:00",
    "start": "2024-02-22",
    "end": null,
    "backgroundColor": null,
    "displayOrder": "4",
    "className": "attendance-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": "nst/934",
    "EmployeeName": "Sarvagya Dubey",
    "ProjectName": null,
    "WeekDayName": "Thursday",
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  },
  {
    "title": "Leave",
    "start": "2024-02-09",
    "end": "2024-02-10",
    "backgroundColor": null,
    "displayOrder": "5",
    "className": "leave-event",
    "AttendanceDate": null,
    "TotalTime": null,
    "ChekInTime": null,
    "CheckOutTime": null,
    "NSTCode": null,
    "EmployeeName": null,
    "ProjectName": null,
    "WeekDayName": null,
    "EmpId": null,
    "TotalHrs": null,
    "StartDate": "\/Date(-62135596800000)\/",
    "PunchIn": null,
    "PunchOut": null,
    "ProjectId": 0
  }
  // { title: 'Meeting', start: new Date() }
]

export function convertDateStringToDdMmYyyy(strDate: any, saperator?: any): any {
  saperator = saperator ? saperator : '/';
  if (strDate != null && strDate !== '') {
    const date: any = new Date(strDate);
    let dd: any = date.getDate();
    let mm: any = date.getMonth() + 1;
    const yyyy = date.getFullYear();
    if (dd < 10) {
      dd = '0' + dd;
    }
    if (mm < 10) {
      mm = '0' + mm;
    }
    return dd + saperator + mm + saperator + yyyy;
  }
  return strDate;
}